Add functions to iterate over content
rossumai/rossum pull request #31
Opened 2021-10-12 11:00 UTC by evelyn9191

This PR creates a new module that contains functions to iterate over content to get various datapoints and larger parts from it.

2021-10-21 14:49 UTC, bara-m commented on rossum/helpers/search_content.py
> +def find_single_datapoint(content: list, schema_id: str) -> dict:
```suggestion
def find_single_datapoint(content: list, schema_id: str) -> Optional[dict]:
```

2021-10-21 14:51 UTC, bara-m commented on rossum/helpers/search_content.py
> +def find_single_datapoint(content: list, schema_id: str) -> dict:
Currently, for single datapoint, this will always return only `id` and `value`. But in some cases, it is useful to have also the `normalized_value`, `page`, `position` or some other.
I would either changed this to always return the whole dict of the datapoint or we can have 2 functions - one will return the whole dict and one only the `id` and `value`.
What do you think?

2021-10-21 14:55 UTC, bara-m commented on rossum/helpers/search_content.py
> +def find_line_items(content: list):
```suggestion
def find_line_items(content: list) -> list:
```

2021-10-21 15:04 UTC, bara-m commented on rossum/helpers/search_content.py
> +def find_multivalue_parent(content: list, schema_id: str) -> dict:
```suggestion
def find_multivalue_parent(content: list, schema_id: str) -> Optional[dict]:
```

2021-10-21 15:14 UTC, bara-m commented
Not sure if we want to add those or not but:
- sometimes we are also looking for all datapoints inside a multivalue header. So you have a `schema_id` of datapoint (that's inside multivalue header) and you want to get all datapoints with that `schema_id` from the content.
- sometimes you want to get list of all rows from a specific LI, because you need to work with line items on a row basis

2021-10-22 11:13 UTC, bara-m commented on rossum/helpers/search_content.py
> +def find_children_of_simple_multivalue(content: list, child_schema_id: str) -> Optional[dict]:
```suggestion
def find_children_of_simple_multivalue(content: list, child_schema_id: str) -> list:
```

2021-10-22 13:26 UTC, bara-m commented on rossum/helpers/search_content.py
> +def find_line_items_rows(content: list, schema_id: str) -> list:
```suggestion
def find_line_items_rows(content: list, schema_id: str) -> Optional[list]:
```

2021-10-22 13:27 UTC, bara-m commented on tests/helpers/test_search_content.py
> +        assert multivalue_parent == SIMPLE_MULTIVALUE_CHILDREN
```suggestion
        multivalue_children = find_children_of_simple_multivalue(
            DEFAULT_SCHEMA, MULTIVALUE_CHILD_NAME
        )
        assert multivalue_children == SIMPLE_MULTIVALUE_CHILDREN
```

2021-10-22 13:28 UTC, bara-m requested changes
See suggestions.

2021-10-22 13:28 UTC, evelyn9191 commented on rossum/helpers/search_content.py
> +def find_all_line_items_datapoints(content: list) -> list:
```suggestion
def find_all_line_items_datapoints(content: list) -> Optional[list]:
```

2021-10-22 13:30 UTC, evelyn9191 commented on rossum/helpers/search_content.py
> +def find_line_items_column(content: list, schema_id: str) -> list:
```suggestion
def find_line_items_column(content: list, schema_id: str) -> Optional[list]:
```

2021-10-22 13:30 UTC, evelyn9191 commented on rossum/helpers/search_content.py
> +def find_children_of_simple_multivalue(content: list, child_schema_id: str) -> list:
```suggestion
def find_children_of_simple_multivalue(content: list, child_schema_id: str) -> Optional[list]:
```

2021-10-22 14:43 UTC, bara-m commented on rossum/helpers/search_content.py
> +def find_all_line_items_datapoints(content: list) -> Optional[list]:
Seems like this is always returning a list - either empty or with some values. Do you know some case when the returned value will be `None`?

2021-10-22 14:43 UTC, bara-m commented on rossum/helpers/search_content.py
> +def find_line_items_column(content: list, schema_id: str) -> Optional[list]:
Same as above.

2021-10-22 14:43 UTC, bara-m commented on rossum/helpers/search_content.py
> +def find_children_of_simple_multivalue(content: list, child_schema_id: str) -> Optional[list]:
Same as above.

2021-10-22 14:56 UTC, bara-m approved these changes

2021-10-22 14:56 UTC, bara-m approved these changes
LGTM.

2021-10-22 14:57 UTC, merged